---

- name: deploy ah frontend
  hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: False
  vars:
    nodejs_version: "11"
    ansible_dest_release: "trusty"
    ansible_python_interpreter: "/usr/bin/python3"

  environment:
    REACT_APP_API: https://ah-codetitans-staging.herokuapp.com/

  tasks:
  - name: Install gpg key for node js
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present

  - name: Add nodejs repo
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_dest_release }} main"
      state: present
      update_cache: yes

  - name: install nginx
    apt:
      name: nginx
      state: latest

  - name: install certbot
    npm:
      name: forever
      global: yes
      state: latest

  - name: install nodejs
    apt:
      name: nodejs
      state: present

  - name: install jest
    npm:
      name: jest
      global: yes
      version: 23.6.0

  # Task to configure nginx
  - name: copy nginx config file
    copy:
      src: ah_config.cfg
      dest: /etc/nginx/sites-available/ah_frontend.cfg

  # Task to create symlink
  - name: create the symlink between default to the new config
    file:
      src: /etc/nginx/sites-available/ah_frontend.cfg
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name : config file to run app in background
    copy:
      src: keep_alive_ah.service
      dest: /lib/systemd/system/keep_alive_ah.service

  # Configure certbot

  # Task to restart nginx with new configs
  - name: restart nginx due to config changes
    shell: |
      sudo /etc/init.d/nginx restart

  # Task to clone the repo
  - name: clone the repo
    git:
      repo: 'https://github.com/andela/ah-code-titans-frontend.git'
      dest: /home/ubuntu/ah-code-titans-frontend
      clone: yes

 # Task to install application dependancies
  - name: Install dependancies
    shell:
      cmd: |
        cd /home/ubuntu/ah-code-titans-frontend
        sudo npm install -ES --unsafe-perm=true


# File to run command
  - name: Bash script to run the application
    shell: |
      touch /home/ubuntu/ah-code-titans-frontend/start_ah.sh && chmod u+x /home/ubuntu/ah-code-titans-frontend/start_ah.sh
      echo "npm run start-js" | tee /home/ubuntu/ah-code-titans-frontend/start_ah.sh

# Start the application
  - name: Start the application
    shell: |
      sudo systemctl daemon-reload
      sudo systemctl start keep_alive_ah
